'I love you!!'
'I miss you!  <3'
'I wish you were here…'
'Hey baby, can’t wait to see you tonight!'
'Hope you are having a good day sweetie!'
'I absolutely love spending time with you!'
'If nothing lasts forever, can I be your nothing?'
'I can’t get you outta my head…'
'You make me laugh when I don’t even want to smile…'
'Loving you is like breathing…How am I supposed to stop?!?!'
'The most incredible feeling is knowing I make you happy!'
'If loving you is wrong, then I don’t wanna be right…'
'I hope that when you read this, it makes you think of me!'
'You make my heart melt!'
'I’ve been thinking about you.'
'I love you, I miss you and I can’t wait to see you today!'